name: CI
on: [pull_request]
permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Ruff
        run: uv run ruff check
  ty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Ty
        run: uv run ty check
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v6

      - name: Build containers
        run: docker compose build

      - name: Run tests
        run: docker compose run --rm oidc-discovery uv run pytest --cov --cov-fail-under=100 -v
